### ISSUE TITLE
asString/string always throws java.lang.UnsupportedOperationException: JsonObject

### ISSUE THREAD

**Issue by sreich** [SalomonBrys/Kotson#24]
`jsonObject("blah" to jsonArray(mutableListOf(1,2,3,4,5))).string`

will always throw:
java.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsString(JsonElement.java:191)

for anything i try. 

vers 2.5.0.

even for the following simplest example.

`jsonObject("a" to 1).string`

**Comment by SalomonBrys** [comment]
You are confusing `string` and `toString`.

It is perfectly normal that you cannot get a `JsonObject` as a `String` since it's a json object, not a json string.

- `.string` gets a JSON string primitive and gets it as a Java `String`.
- `.toString()` "stringifies" a JSON value (array, object or primitive) into a JSON serialized String.
