### ISSUE TITLE
Rethink name

### ISSUE THREAD

**Issue by cypressious** [SalomonBrys/Kotson#5]
I just wanted you to know, that the name of the library "Kotson", when pronounced, unfortunately sounds exactly like the german verb "[kotzen](https://de.wiktionary.org/wiki/kotzen)" which means "to puke" or "to vomit".

This makes it kinda hard to stay serious when coding with your team mates because everytime the name is mentioned, someone has to laugh. Additionally, this seems to amplify, everytime it happens :)

**Comment by SalomonBrys** [comment]
Hahahahaha!
Now I definitely don't want to change the name :laughing:.

Seriously, though, I'm not sure it's a good enough reason to change the name. There are many (natural) languages in this world, any name can easily be close to something like that.

Anyway, I'm leaving this open so that I can ask everybody this: What better name can you think of?
If any is convincing, then I'll consider changing Kotson's name ;)

**Comment by cypressious** [comment]
My suggestion: KSON

**Comment by yoavst** [comment]
KSON is a very good name, but I think It is better to leave it for pure Kotlin JSON library, not just for Gson extenstions :)

**Comment by cypressious** [comment]
How about KGSON, pronounced "Ka-Geeson" 😀?

Kirill Rakhman
Am 24.10.2015 1:02 nachm. schrieb "Yoav Sternberg" <notifications@github.com

**Comment by yoavst** [comment]
Kgson is great.

**Comment by westito** [comment]
Koton (-s) means "condom" in hungary :D

**Comment by sfunke** [comment]
Kgson :+1: :+1: :+1: 

Being german, I'm strongly with @cypressious on this one! 
(Let alone, the name of the language "Kotlin" itself is not german language friendly and rises some eyebrows here and there (Kot == poo), but well, I guess we'll have to adapt on that, since it's explicitly named after the Russian island).

But "Kotson" - well, @cypressious explained it :-)

Basically anything that starts with "Kot.." won't be much appreciated by german speaking folks I guess...

**Comment by sanity** [comment]
How about Crapson? ;P

**Comment by SalomonBrys** [comment]
OK, this has been fun, but the truth is I'm not willing to change the package name of the library and therefore its name, sorry.

I realise this is not ideal for German coders, but you know, there are lots of [libraries that have weird names](http://caca.zoy.org/wiki/libcaca), including in French.

At least I'll be responsible for some laugh at the office ;)
